# Page settings
publishDir = "dist"

baseurl = "//lorenghoh.github.io/"
languageCode = "en-us"
theme = "orbit"
#googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = false

[params]
title = "Loren Oh"

# Meta
description = "Personal CV Webpage for Loren Oh"
author = "Loren Oh"

# Theme styles
styles = "stylesheet.css"

# Sidebar sections
# Profile section
[params.profile]
name = "Loren Oh"
tagline = "Computational Physicist"
avatar = "profile.png"

# Contact section
[params.contact]
enable = true

[[params.contact.list]]
class = "email"
icon = "fa fa-envelope"
url = "mailto: loh@eoas.ubc.ca"
title = "loh@eoas.ubc.ca"

[[params.contact.list]]
class = "github"
icon = "fab fa-github"
url = "//github.com/lorenghoh"
title = "github.com/lorenghoh"

[[params.contact.list]]
class = "website"
icon = "fa fa-university"
url = "//www.eoas.ubc.ca/people/gunholorenoh"
title = "lorenghoh.github.io"

[[params.contact.list]]
class = "linkedin"
icon = "fab fa-linkedin"
url = "//linkedin.com/in/lorenghoh"
title = "linkedin.com/in/lorenghoh"

# Interests section
# [params.interests]
# enable = true
# title = "Interests"

# [[params.interests.list]]
# interest = "Cloud Physics"

# [[params.interests.list]]
# interest = "Large-eddy Simulation"

# [[params.interests.list]]
# interest = "Machine Learning"

# [[params.interests.list]]
# interest = "Big Data Analysis"

# [[params.interests.list]]
# interest = "Optimization"

# [[params.interests.list]]
# interest = "Logic"

# Main matter
# You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

# Summary section
[params.summary]
enable = true
icon = "fa-user-graduate"
title = "Profile"

# Education section
[params.education]
enable = true
icon = "fa-graduation-cap"
title = "Education"

[[params.education.list]]
college = "University of British Columbia"
degree = "Combined Honours in Computer Science and Physics"
dates = "2008 - 2012"

[[params.education.list]]
college = "McGill University"
degree = "M.Sc. in Atmospheric Sciences"
dates = "2012 - 2014"

[[params.education.list]]
college = "University of British Columbia"
degree = "Ph.D. in Atmospheric Sciences"
dates = "2014 - now"

# Projects section
[params.projects]
enable = true
icon = "fa-wrench"
title = "Projects"
intro = "Some of my public, open-source projects. Mostly written in Python."

[[params.projects.list]]
title = "Fractal Analysis for Cumulus Clouds"
links = ["//github.com/lorenghoh/fractal_clouds", "//cdn.rawgit.com/lorenghoh/fractal_clouds/13e63bb7/notebook/fractal_clouds.html"]
description = "Analysis of fractal properties observed in individual boundary-layer cumulus clouds, modelled by a high-resolution large-eddy simulation."
icons = ["fab fa-github-square", "fas fa-bars"]
tags = [""]

[[params.projects.list]]
title = "Gaussian Process Regression for Periodicity Detection"
links = ["//github.com/lorenghoh/gaussian_processes_ams_2018", "//github.com/lorenghoh/gaussian_processes_ams_2018/blob/master/notebooks/gaussian_regression.html"]
description = "Using GP regression methods to identify and analyze oscillatory motions in the cloud size distribution measured from a simulated cloud field using a high-resolution large-eddy simulation."
icons = ["fab fa-github-square", "fas fa-bars"]

[[params.projects.list]]
title = "Statistical Distribution of Modelled Cumulus Cloud Clusters"
links = ["//github.com/lorenghoh/cloud_clusters"]
description = "A statistically more robust algorithm to estimate the cloud size distribution of a modelled cloud field."
icons = ["fab fa-github-square"]

[[params.projects.list]]
title = "ATLAS - 3D Trajectory Clustering Algorithm"
links = ["//github.com/lorenghoh/atlas"]
description = "A cloud-tracking algorithm based on trajectory clustering, data analysis and machine learning (in development)."
icons = ["fab fa-github-square"]

[[params.projects.list]]
title = "NLP-based Plagiarism Checker"
links = ["//github.com/lorenghoh/eosc_340_nlp"]
description = "A simple, customizable NLP project using TF-IDF to check for plagiarism."
icons = ["fab fa-github-square"]

# Publications section
[params.publications]
enable = true
icon = "fa-book"
title = "Publications"

[[params.publications.list]]
title = "Comparison of the Theoretical and Computational Estimates of the Momentum Budget in Shallow Cumulus Clouds"
dates = "2012"
url = "/papers/momentum_budget"
journal = "Honours Thesis"
publisher = "University of British Columbia"

[[params.publications.list]]
title = "Improving Kain-Fritsch Convective Parameterization Using Direct Calculations of Entrainment and Detrainment in Shallow and Deep Convection"
dates = "2014"
url = "/papers/kain-fritsch"
journal = "MSc Thesis"
publisher = "McGill University"

[[params.publications.list]]
title = "On the Relationship Between Individual Cloud Entrainment Probability Density Functions and the Mean Field Behaviour"
dates = "2018"
journal = "In Preparation"
publisher = "J. Atmospheric Sci."

[[params.publications.list]]
title = "Entrainment as a Measure of Dilution"
dates = "2018"
journal = "In Preparation"
publisher = "J. Atmospheric Sci."

[[params.publications.list]]
title = "Quantifying the Oscillatory Evolution of Simulated Boundary-Layer  Cloud Fields Using Gaussian Processes"
dates = "2019"
journal = "In Preparation"
publisher = "J. Atmospheric Sci."

# Talks section
[params.talks]
enable = true
icon = "fa-quote-left"
title = "Talks"

[[params.talks.list]]
title = "Direct Entrainment and Detrainment Rate Distributions of Individual Clouds in Deep Marine Tropical Convection"
url = ""
date = "2015"
location = "49th CMOS Congress"
type = "Conference"

[[params.talks.list]]
title = "Resolved Entrainment and Dilution Calculations for Individually Tracked Boundary Layer Clouds"
url = "//ams.confex.com/ams/32AgF22BLT3BG/webprogram/Paper295982.html"
date = "2016"
location = "23rd Symposium on Boundary Layers and Turbulence"
type = "Conference"

[[params.talks.list]]
title = "Quantifying the Oscillatory Evolution of Simulated Boundary-Layer Cloud Fields Using Gaussian Processes"
url = "//ams.confex.com/ams/15CLOUD15ATRAD/webprogram/Paper347741.html"
date = "2018"
location = "15th Conference on Cloud Physics"
type = "Conference"

[[params.talks.list]]
title = "The Role of Moist Shells in Determining the Dilution of Cumulus Clouds"
url = "//ams.confex.com/ams/15CLOUD15ATRAD/webprogram/Paper347701.html"
date = "2018"
location = "15th Conference on Cloud Physics"
type = "Conference"

# Teaching section
[params.teaching]
enable = true
icon = "fa-chalkboard-teacher"
title = "Teaching"

# Skills section
[params.skills]
enable = true
icon = "fa-coffee"
title = "Skills & Proficiency"

[[params.skills.list]]
skill = "Python"
level = "98%"

[[params.skills.list]]
skill = "Julia"
level = "90%"
        
[[params.skills.list]]
skill = "C/C++"
level = "95%"

[[params.skills.list]]
skill = "Fortran"
level = "90%"

[[params.skills.list]]
skill = "Java"
level = "90%"

[[params.skills.list]]
skill = "Ruby"
level = "80%"

[[params.skills.list]]
skill = "HTML5 & CSS"
level = "90%"

# Footer section

# The original template is released under the Creative Commons Attribution 3.0 License.
# Please keep the original attribution link when using for your own project.
# If you'd like to use the template without the attribution,
# you can check out other license options via template author's website: themes.3rdwavemedia.com
# 
# As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

[params.footer]
    copyright = ""
